#!/bin/sh
#
# OpenIPC.org | 2024
#

MODULE=/lib/modules/4.9.84/sigmastar
SENSOR=$(fw_printenv -n sensor)

detect_sensor() {
	insmod $MODULE/sensor_config.ko
	retries=0
	while [ $retries -lt 10 ]; do
		if [ -e /dev/srcfg ]; then
			echo srcfg 0 1 0 0 0 0 > /dev/srcfg
			sleep 1
			SENSOR=$(ipcinfo -s)
			if [ -n "$SENSOR" ]; then
				break
			fi
		fi
		sleep 1
		retries=$((retries + 1))
	done
	rmmod sensor_config 2>/dev/null
	if [ -z "$SENSOR" ]; then
    echo "Sensor auto-detection failed, trying to find any sensor driver..." | logger -s -t OpenIPC
    # 在模块目录下查找 sensor_*_mipi.ko 文件，提取传感器名
    for ko in $MODULE/sensor_*_mipi.ko; do
        if [ -f "$ko" ]; then
            # 去掉路径和前后缀，得到类似 jxq03 的字符串
            SENSOR=$(basename "$ko" | sed 's/^sensor_\(.*\)_mipi\.ko$/\1/')
            break
        fi
    done
    if [ -z "$SENSOR" ]; then
        echo "No sensor driver found! Giving up." | logger -s -t OpenIPC
        exit 1
    else
        echo "Using sensor from driver file: $SENSOR" | logger -s -t OpenIPC
    fi
	fi
	fw_setenv sensor "$SENSOR"
}

set_sensor() {
	case $SENSOR in
		gc2053|gc2083|gc4023|gc4653|imx307|imx335|jxf37|jxq03|os02g10)
			insmod $MODULE/sensor_${SENSOR}_mipi.ko chmap=1
			;;
		sc200ai|sc401ai|sc2239|sc223a|sc2335|sc2336|sc3335|sc3336|sc3338)
			insmod $MODULE/sensor_${SENSOR}_mipi.ko chmap=1
			;;
		*)
			echo -e "\n\e[1;31mUNSUPPORTED sensor - $SENSOR\e[0m\n" | logger -s -t OpenIPC
			;;
	esac
}

insert_ko() {
	insmod $MODULE/mhal.ko
	insmod $MODULE/mi_common.ko
	insmod $MODULE/mi_sys.ko cmdQBufSize=256 logBufSize=256
	insmod $MODULE/mi_rgn.ko
	insmod $MODULE/mi_ai.ko
	insmod $MODULE/mi_ao.ko
	insmod $MODULE/mi_sensor.ko
	insmod $MODULE/mi_shadow.ko
	insmod $MODULE/mi_divp.ko
	insmod $MODULE/mi_vif.ko
	insmod $MODULE/mi_vpe.ko
	insmod $MODULE/mi_venc.ko fw_path=/etc/firmware/chagall.bin

	MAJOR=$(awk '$2=="mi_poll" {print $1}' /proc/devices)
	mknod /dev/mi_poll c "$MAJOR" 0
	echo isproot /etc/firmware > /dev/ispmid
}

if [ ! -e /sys/module/mi_common ]; then
	insert_ko
fi

if [ -z "$1" ] || [ -z "$SENSOR" ]; then
	echo -e "\n\e[1;33mAutodetect sensor\e[0m\n" | logger -s -t OpenIPC
	detect_sensor
fi

if [ -z "$SENSOR" ]; then
	echo -e "\n\e[1;31mSensor parameter MISSING\e[0m\n" | logger -s -t OpenIPC
	exit 1
fi

DRIVER=$(ls /sys/module | grep $SENSOR)
if [ -n "$DRIVER" ]; then
	rmmod $DRIVER
fi

echo -e "\n\e[1;32mSensor assigned - $SENSOR\e[0m\n" | logger -s -t OpenIPC
set_sensor

exit 0
