#!/bin/sh

start() {
    /usr/bin/night_watchdog.sh &
}

stop() {
    killall night_watchdog.sh 2>/dev/null
}

case "$1" in
    start|stop)
        $1
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
